/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Models.Table;

/**
 *
 * @author Andrey
 */
public class BoardFrame extends javax.swing.JFrame {
    // Instanciando a classe Table
    Table table = new Table(Main.players.get(0), Main.players.get(1));

    /**
     * Creates new form Board
     */
    public BoardFrame() {
        initComponents();
        // Iniciando o jogo com o jogador atual
        table.checkTurn(turnText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board1 = new javax.swing.JPanel();
        turnText = new javax.swing.JLabel();
        board2 = new javax.swing.JPanel();
        firstButton = new javax.swing.JButton();
        secondButton = new javax.swing.JButton();
        thirdButton = new javax.swing.JButton();
        firstButton2 = new javax.swing.JButton();
        secondButton2 = new javax.swing.JButton();
        thirdButton2 = new javax.swing.JButton();
        firstButton3 = new javax.swing.JButton();
        secondButton3 = new javax.swing.JButton();
        thirdButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        board1.setBackground(java.awt.Color.white);

        turnText.setLabelFor(board1);
        turnText.setText("Null");

        firstButton.setToolTipText("Empty");
        firstButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstButtonMouseClicked(evt);
            }
        });
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        secondButton.setToolTipText("Empty");
        secondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondButtonActionPerformed(evt);
            }
        });

        thirdButton.setToolTipText("Empty");
        thirdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdButtonActionPerformed(evt);
            }
        });

        firstButton2.setToolTipText("Empty");
        firstButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButton2ActionPerformed(evt);
            }
        });

        secondButton2.setToolTipText("Empty");
        secondButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondButton2ActionPerformed(evt);
            }
        });

        thirdButton2.setToolTipText("Empty");
        thirdButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdButton2ActionPerformed(evt);
            }
        });

        firstButton3.setToolTipText("Empty");
        firstButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButton3ActionPerformed(evt);
            }
        });

        secondButton3.setToolTipText("Empty");
        secondButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondButton3ActionPerformed(evt);
            }
        });

        thirdButton3.setToolTipText("Empty");
        thirdButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout board2Layout = new javax.swing.GroupLayout(board2);
        board2.setLayout(board2Layout);
        board2Layout.setHorizontalGroup(
                board2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(board2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(board2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(board2Layout.createSequentialGroup()
                                                .addComponent(firstButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(secondButton2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(thirdButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, board2Layout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(board2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                board2Layout.createSequentialGroup()
                                                                        .addComponent(firstButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(secondButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(thirdButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                board2Layout.createSequentialGroup()
                                                                        .addComponent(firstButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(secondButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(thirdButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap()));
        board2Layout.setVerticalGroup(
                board2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(board2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(board2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secondButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(thirdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(board2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secondButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(thirdButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(board2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secondButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(thirdButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout board1Layout = new javax.swing.GroupLayout(board1);
        board1.setLayout(board1Layout);
        board1Layout.setHorizontalGroup(
                board1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(board1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(board1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(board2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(board1Layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(turnText, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        board1Layout.setVerticalGroup(
                board1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(board1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(board2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(turnText, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(53, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(board1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(board1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void secondButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_secondButtonActionPerformed
        table.makePlay(secondButton, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_secondButtonActionPerformed

    private void secondButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_secondButton2ActionPerformed
        table.makePlay(secondButton2, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_secondButton2ActionPerformed

    private void secondButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_secondButton3ActionPerformed
        table.makePlay(secondButton3, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_secondButton3ActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_firstButtonActionPerformed
        table.makePlay(firstButton, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_firstButtonActionPerformed

    private void firstButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_firstButtonMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_firstButtonMouseClicked

    private void thirdButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thirdButton3ActionPerformed
        table.makePlay(thirdButton3, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_thirdButton3ActionPerformed

    private void thirdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thirdButtonActionPerformed
        table.makePlay(thirdButton, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_thirdButtonActionPerformed

    private void firstButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_firstButton2ActionPerformed
        table.makePlay(firstButton2, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_firstButton2ActionPerformed

    private void thirdButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thirdButton2ActionPerformed
        table.makePlay(thirdButton2, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_thirdButton2ActionPerformed

    private void firstButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_firstButton3ActionPerformed
        table.makePlay(firstButton3, turnText);
        table.matchCheck(firstButton, firstButton2, firstButton3, secondButton, secondButton2, secondButton3,
                thirdButton, thirdButton2, thirdButton3, turnText);
    }// GEN-LAST:event_firstButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new BoardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel board1;
    private javax.swing.JPanel board2;
    private javax.swing.JButton firstButton;
    private javax.swing.JButton firstButton2;
    private javax.swing.JButton firstButton3;
    private javax.swing.JButton secondButton;
    private javax.swing.JButton secondButton2;
    private javax.swing.JButton secondButton3;
    private javax.swing.JButton thirdButton;
    private javax.swing.JButton thirdButton2;
    private javax.swing.JButton thirdButton3;
    private javax.swing.JLabel turnText;
    // End of variables declaration//GEN-END:variables
}
